"use client";

import { useState } from "react";
import type { AuditResult } from "@/lib/schema";

export function ShareButtons({
  decision,
  result,
}: {
  decision: string;
  result: AuditResult;
}) {
  const [copied, setCopied] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [sharing, setSharing] = useState(false);

  const boardBrief = `StratOS Lite — London Royal Academy Decision Audit

Decision: ${decision}

Type: ${result.decision_type}
Verdict: ${result.verdict}
Confidence: ${result.confidence_score}/100

Biggest Risk:
${result.biggest_risk}

Hidden Assumption:
${result.hidden_assumption}

Better Question:
${result.better_question}

30-Day Test:
${result.thirty_day_test}

Devil's Argument:
${result.devils_argument}

Generated by StratOS Lite
ai.londonra.com`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(boardBrief);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = async () => {
    const res = await fetch("/api/pdf", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ decision, result }),
    });
    if (!res.ok) return;
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "stratos-lite-audit.pdf";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (shareUrl) {
      await navigator.clipboard.writeText(
        `${window.location.origin}${shareUrl}`
      );
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      return;
    }
    setSharing(true);
    try {
      const res = await fetch("/api/share", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ decision, result }),
      });
      if (!res.ok) return;
      const data = await res.json();
      setShareUrl(data.url);
      const fullUrl = `${window.location.origin}${data.url}`;
      await navigator.clipboard.writeText(fullUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } finally {
      setSharing(false);
    }
  };

  return (
    <div className="flex flex-wrap gap-3 justify-center pt-2">
      <ShareBtn onClick={handleCopy}>
        {copied ? "Copied!" : "Copy Board Brief"}
      </ShareBtn>
      <ShareBtn onClick={handleDownloadPdf}>Download PDF</ShareBtn>
      <ShareBtn onClick={handleShare} disabled={sharing}>
        {sharing ? "Creating…" : shareUrl ? "Copy Share Link" : "Share Link"}
      </ShareBtn>
    </div>
  );
}

function ShareBtn({
  children,
  onClick,
  disabled,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className="px-4 py-2 text-xs uppercase tracking-wider border border-gray-300 rounded-md
        hover:border-[#b8a260] hover:text-[#b8a260] transition-colors
        disabled:opacity-50 disabled:cursor-not-allowed"
    >
      {children}
    </button>
  );
}
